SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS CATALOGUE;
DROP TABLE IF EXISTS REGISTRATIONS;

CREATE TABLE PERSON (
	net_id VARCHAR(10) PRIMARY KEY,
	empl_id INTEGER,
	common_name VARCHAR(50),
	email VARCHAR(50),
    role_id INTEGER,
    department_id INTEGER
);

CREATE TABLE ROLES (
	role_id INTEGER PRIMARY KEY,
	role_name VARCHAR(20)
);

CREATE TABLE DEPARTMENTS (
	department_id INTEGER PRIMARY KEY,
    department_name VARCHAR(20)
);

CREATE TABLE CATALOGUE (
    workshop_id INTEGER PRIMARY KEY,
    workshop_host_id VARCHAR(10),
    department_id INTEGER,
    title VARCHAR(100),
    details VARCHAR(500),
    location VARCHAR(200),
    start_time DATETIME,
	end_time DATETIME
);

CREATE TABLE REGISTRATIONS (
	workshop_id INTEGER PRIMARY KEY,
    net_id VARCHAR(10)
);

-- Constraints for table PERSON
ALTER TABLE PERSON ADD CONSTRAINT FOREIGN KEY (role_id) REFERENCES ROLES (role_id);
ALTER TABLE PERSON ADD CONSTRAINT FOREIGN KEY (department_id) REFERENCES DEPARTMENTS (department_id);

-- Constraints for table ROLES
-- none

-- Constraints for table DEPARTMENTS
-- none

-- Constraints for table CATALOGUE
ALTER TABLE CATALOGUE ADD CONSTRAINT FOREIGN KEY (workshop_host_id) REFERENCES PERSON (net_id);
ALTER TABLE CATALOGUE ADD CONSTRAINT FOREIGN KEY (department_id) REFERENCES DEPARTMENTS (department_id);

-- Constraints for table REGISTRATIONS
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FOREIGN KEY (workshop_id) REFERENCES CATALOGUE (workshop_id);
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FOREIGN KEY (net_id) REFERENCES PERSON (net_id);

-- ADD STUFF
INSERT INTO ROLES VALUES (2, "Facilitator");
INSERT INTO DEPARTMENTS VALUES (2, "ArtSci");
INSERT INTO PERSON VALUES ("5daniel", 1014, "Daniel K.", "daniel@hotmail.com", 2, 2);
INSERT INTO CATALOGUE VALUES (1, 2, 2, "Title", "Details", "Location", '2019-04-01 14:00:00', '2019-04-01 16:00:00');